name: 'CI'

on:
  push:
    branches:
      - main

# defaults: ถ้าหากอยากเอาไฟล์ ci.yml ไปไว้ที่อื่นให้ใช้คำสั่งนี้
#   run:
#     working-directory: ./app

jobs:
  lint-job: # name jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set nodejs version to 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Format
        run: npm run format

  unit-test-job: # name jobs
    runs-on: ubuntu-latest
    needs: lint-job
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v4

      - name: Test on ${{matrix.os}} nodejs version to ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'

      - run: npm ci

      - name: Run Unit Test
        run: npm run test:unit
